apiVersion: run.ai/v2alpha1  # Specifies the version of the Run.ai API this resource is written against.
kind: TrainingWorkload  # Specifies the kind of resource, in this case, a Run.ai Job.
metadata:
  name: hello1  # The name of the job.
  namespace: runai-ml4ed-frej  # The namespace in which the job will be created.
  labels:
    user: frej  # REPLACE Tequila user
spec:
  image:
    value: ic-registry.epfl.ch/d-vet/helloworld-image
  name:
    value: hello1  # name prefix of Pod
  arguments:  # Arguments passed to the container, space-separated, if the argument has spaces, use quotes as below.
    value: "--text \"Goodbye World\""
  runAsUser:
    value: true
  allowPrivilegeEscalation:  # allow sudo
    value: true
  cpu:
    value: "1"
  cpuLimit:
    value: "1"
  memory:
    value: 256Mi
  memoryLimit:
    value: 512Mi
  gpu:
    value: "0"
  nodePools:
    value: "default" # default is the node type S8 without GPUs
  pvcs:
    items:
      pvc--0:  # First is "pvc--0", second "pvc--1", etc.
        value:
          claimName: runai-ml4ed-frej-ml4eddata1
          existingPvc: true
          path: /data